### ISSUE TITLE
Express 2 Lesson Plan Checklist

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#494]
Components
- [x] Learning Objectives
- [x] Framing
- [x] Scaffolded
- [x] Timing
- [x] frequent CFUs
  - [ ] with suggested mode (Turn and Talk, etc)
- [x] Exercises
- [ ] Homework
- [ ] Summary/Cliff Notes
- [ ] Questions (for quiz or slips)
- [x] Outside resources: a few links
- [ ] Cheatsheets, optional
  - [ ] e.g. [variables.md](https://github.com/ga-dc/pbj/blob/master/04-ruby-mvc-sinatra/object_oriented_programming_in_ruby/variables.md)

Constraints

- [ ] Written in a textbook/manual fashion
- [ ] Reviewed by Peer
- [ ] Update SUMMARY.md (for gitbook)
