### ISSUE TITLE
OOJS 2 Lesson Plan Checklist

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#497]
Components
- [x] Learning Objectives
- [x] Framing
- [x] Scaffolded
- [ ] Timing
- [x] frequent CFUs
  - [ ] with suggested mode (Turn and Talk, etc)
- [x] Exercises
- [x] Homework
- [x] Summary/Cliff Notes
- [x] Questions (for quiz or slips)
- [x] Outside resources: a few links
- [ ] Cheatsheets, optional
  - [ ] e.g. [variables.md](https://github.com/ga-dc/pbj/blob/master/04-ruby-mvc-sinatra/object_oriented_programming_in_ruby/variables.md)

Constraints

- [x] Written in a textbook/manual fashion
- [ ] Reviewed by Peer
- [x] Update SUMMARY.md (for gitbook)
