### ISSUE TITLE
TDD Lesson Planning Checklist

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#498]
Components
- [x] Learning Objectives
- [x] Framing
- [x] Scaffolded
- [x] Timing
- [x] frequent CFUs
  - [ ] with suggested mode (Turn and Talk, etc)
- [x] Exercises
- [x] Homework
- [x] Summary/Cliff Notes
- [x] Questions (for quiz or slips)
- [x] Outside resources: a few links
- [x] Cheatsheets, optional
  - [ ] e.g. [variables.md](https://github.com/ga-dc/pbj/blob/master/04-ruby-mvc-sinatra/object_oriented_programming_in_ruby/variables.md)

Constraints

- [x] Written in a textbook/manual fashion
- [x] Reviewed by Peer
- [x] Update SUMMARY.md (for gitbook)

**Comment by adambray** [comment]
@ebirving @RobertAKARobin just a friendly ping to use this checklist!

**Comment by RobertAKARobin** [comment]
2/10 Would prefer unfriendly ping.
