### ISSUE TITLE
User Auth with Passport Lesson Checklist

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#499]
Components
- [ ] Learning Objectives
- [ ] Framing
- [ ] Scaffolded
- [ ] Timing
- [ ] frequent CFUs
  - [ ] with suggested mode (Turn and Talk, etc)
- [ ] Exercises
- [ ] Homework
- [ ] Summary/Cliff Notes
- [ ] Questions (for quiz or slips)
- [ ] Outside resources: a few links
- [ ] Cheatsheets, optional
  - [ ] e.g. [variables.md](https://github.com/ga-dc/pbj/blob/master/04-ruby-mvc-sinatra/object_oriented_programming_in_ruby/variables.md)

Constraints

- [ ] Written in a textbook/manual fashion
- [ ] Reviewed by Peer
- [ ] Update SUMMARY.md (for gitbook)
