### ISSUE TITLE
Responsive Web Design Lesson Planning Checklist

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#501]
Components
- [x] Learning Objectives
- [x] Framing
- [x] Scaffolded
- [x] Timing
  - [x] Sufficient Breaks
- [ ] frequent [CFUs](https://docs.google.com/document/u/1/d/1M6vqcYtiBoTkoL_yYurb7YCEIXlXln0v1wi8Ol0B7XY/edit?usp=drive_web)
  - [x] with suggested mode (Turn and Talk, etc)
- [x] Exercises
- [x] Homework.md updated
- [x] Summary/Cliff Notes
- [x] Questions (for quiz or slips)
- [x] Outside resources: a few links
- [ ] Cheatsheets, optional
  - [ ] e.g. [variables.md](https://github.com/ga-dc/pbj/blob/master/04-ruby-mvc-sinatra/object_oriented_programming_in_ruby/variables.md)

Constraints

- [x] Written in a textbook/manual fashion
- [ ] Reviewed by Peer
- [ ] Update SUMMARY.md (for gitbook)
