### ISSUE TITLE
LP Checklist: Angular Custom Directives

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#563]
Components
- [x] Learning Objectives
- [x] Framing
- [x] Scaffolded
- [x] Timing
  - [ ] Sufficient Breaks
- [x] frequent [CFUs](https://docs.google.com/document/u/1/d/1M6vqcYtiBoTkoL_yYurb7YCEIXlXln0v1wi8Ol0B7XY/edit?usp=drive_web)
  - [ ] with suggested mode (Turn and Talk, etc)
- [x] Exercises
- [ ] Homework.md updated
- [ ] Summary/Cliff Notes
- [x] Questions (for quiz or slips)
- [ ] Outside resources: a few links
- [ ] Cheatsheets, optional
  - [ ] e.g. [variables.md](https://github.com/ga-dc/pbj/blob/master/04-ruby-mvc-sinatra/object_oriented_programming_in_ruby/variables.md)

Constraints

- [x] Written in a textbook/manual fashion
- [x] Reviewed by Peer
- [ ] Update SUMMARY.md (for gitbook)
