### ISSUE TITLE
LP Checklist: Angular Authentication with Tokens

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#564]
Components
- [ ] Learning Objectives
- [ ] Framing
- [ ] Scaffolded
- [ ] Timing
  - [ ] Sufficient Breaks
- [ ] frequent [CFUs](https://docs.google.com/document/u/1/d/1M6vqcYtiBoTkoL_yYurb7YCEIXlXln0v1wi8Ol0B7XY/edit?usp=drive_web)
  - [ ] with suggested mode (Turn and Talk, etc)
- [ ] Exercises
- [ ] Homework.md updated
- [ ] Summary/Cliff Notes
- [ ] Questions (for quiz or slips)
- [ ] Outside resources: a few links
- [ ] Cheatsheets, optional
  - [ ] e.g. [variables.md](https://github.com/ga-dc/pbj/blob/master/04-ruby-mvc-sinatra/object_oriented_programming_in_ruby/variables.md)

Constraints

- [ ] Written in a textbook/manual fashion
- [ ] Reviewed by Peer
- [ ] Update SUMMARY.md (for gitbook)
